apiVersion: v1
kind: Config
clusters:
- name: msp-spring-2025
  cluster:
    insecure-skip-tls-verify: true
    server: https://hcp-6da04d29-ab65-4bdf-9b23-cb2b79f0ff70.spot.rackspace.com/
contexts:
- name: aqib420-dev
  context:
    cluster: msp-spring-2025
    namespace: aqib420-dev
    user: aqib420-dev-sa
current-context: aqib420-dev
users:
- name: aqib420-dev-sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjVEQkViOVlUelhWVk1xbzN4UnRwMmM3QktoUVBnSTFsRWItMFdmT0ZhNGMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhcWliNDIwLWRldiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhcWliNDIwLWRldi1zYS10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhcWliNDIwLWRldi1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjJjMDdlNWVmLTc3NTctNGE1OS1iMzY3LTkyOTgwOTAyYjkxYyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDphcWliNDIwLWRldjphcWliNDIwLWRldi1zYSJ9.fzRdZgngIsFVaeCk_d1CIW7btue11O0Kns_3Mh_dlt4fk78UXyQuIaPdYvvk_wgNJSpVsoengX-uiCQOm62C6QX6nEZ-7M-B5yfc7YSHFI1889KmYIKRoXmI62KQQAq4wqBhFivbX0DEDPO3ubhJ2h7x0wmNCXP-ws3XZdXN-G_0XPSfVbzTHKbmCWckk3f4765VOO5u_JBVggrHYVFsyd9wdxqxq0gnbfJKIUN8-8Rn0zA1_XqEFRqWt7Zi6jeqB5HQsPSlgkCkbKKZ6DkUFxCBnQsqg3B5Eb6VVTYa5KA_JbEbKnNmpySVYjUaXZu0rvjksX2ChfaKY5eaTuC0SQ
