apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: default
data:
  config.yaml: |
    tunnel: {{ .Values.cloudflare.tunnelId }}
    credentials-file: /etc/cloudflared/credentials/credentials.json
    ingress:
      {{- range .Values.students }}
      - hostname: {{ .id }}-dev-web-svc.{{ $.Values.baseDomain }}
        service: http://web-svc.{{ .id }}-dev.svc.cluster.local:80
      - hostname: {{ .id }}-prod-web-svc.{{ $.Values.baseDomain }}
        service: http://web-svc.{{ .id }}-prod.svc.cluster.local:80
      {{- end }}
