# Workflow to build and deploy docker image
# use these actions for docker image:
#      https://github.com/docker/login-action/tree/v2/
#      https://www.github.com/docker/build-push-action/tree/v4/
# The docker image tag should be ghcr.io/${{ github.repository }}:${{github.sha}}
# For docker login, use github.actor and secrets.GITHUB_TOKEN
# use these actions for kubernetes:
#      https://github.com/Azure/setup-kubectl
#      https://github.com/Azure/setup-helm

# If you see "ERROR: denied: installation not allowed to Create organization package", add permissions under runs-on:
#  runs-on: ubuntu-latest
#  permissions:
#      contents: read
#      packages: write

# As you progress, only uncomment lines that are needed depending on where you are in the project.

name: Build and Deploy

on:
  push:
    branches:
      - main  #workflow runs when changes get pushed to main branch

jobs:
    build-docker-image:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write

        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Login to github registry
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Build and push docker image
            uses: docker/build-push-action@v4
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

    deploy-to-dev:
        runs-on: ubuntu-latest
        needs: build-docker-image
        steps:
          - name: install kubectl
            uses: Azure/setup-kubectl@v1
            with:
              version: 'latest'

          - name: install helm
            uses: Azure/setup-helm@v1
            with:
              version: 'latest'