# TODO: Create a production release workflow
# If you see "ERROR: denied: installation not allowed to Create organization package", add permissions under runs-on:
#  runs-on: ubuntu-latest
#  permissions:
#      contents: read
#      packages: write

# As you progress, only uncomment lines that are needed depending on where you are in the project.

# name: Deploy to Prod
# on:
#   # add triggers here
# jobs:
#     retag-image:
#         runs-on: ubuntu-latest
#         permissions:
#           contents: read
#           packages: write
#         steps:
#           # add steps here
#     deploy-to-prod:
#         runs-on: ubuntu-latest
#         needs: retag-image
#         steps:
#           # add steps here