{{/* 
TODO: Create deployment of portfolio application
The manifest can access values from values.yaml file by enclosing them with double curly braces {{ }}
For example, {{ .Values.replicaCount }}. So instead of hard coding replicas: 1, you will use replicas: {{ .Values.replicaCount }}.
Helm will automatically replace the value of .Values.replicaCount with the value from values.yaml file.

Edit the following as required but keep the resources section unchanged.

Hint: start with simple deployment Yaml and replace dynamic values later with {{ .Values.X }}
*/}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: {{ .Values.githubUsername }}-{{ .Values.environment }}
  labels:
    app: portfolio
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          # add other containers fields below
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent"}}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: environment
              value: {{ .Values.environment }}
    
          # DO NOT MODIFY BELOW THIS LINE
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # DO NOT MODIFY ABOVE THIS LINE
